// flow-typed signature: e67369c1cb3456055e83057b2ad25559
// flow-typed version: <<STUB>>/mpvue-webpack-target_v^1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mpvue-webpack-target'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mpvue-webpack-target' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mpvue-webpack-target/JsonpChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'mpvue-webpack-target/JsonpHotUpdateChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'mpvue-webpack-target/JsonpMainTemplate.runtime' {
  declare module.exports: any;
}

declare module 'mpvue-webpack-target/JsonpMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'mpvue-webpack-target/JsonpTemplatePlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mpvue-webpack-target/index' {
  declare module.exports: $Exports<'mpvue-webpack-target'>;
}
declare module 'mpvue-webpack-target/index.js' {
  declare module.exports: $Exports<'mpvue-webpack-target'>;
}
declare module 'mpvue-webpack-target/JsonpChunkTemplatePlugin.js' {
  declare module.exports: $Exports<'mpvue-webpack-target/JsonpChunkTemplatePlugin'>;
}
declare module 'mpvue-webpack-target/JsonpHotUpdateChunkTemplatePlugin.js' {
  declare module.exports: $Exports<'mpvue-webpack-target/JsonpHotUpdateChunkTemplatePlugin'>;
}
declare module 'mpvue-webpack-target/JsonpMainTemplate.runtime.js' {
  declare module.exports: $Exports<'mpvue-webpack-target/JsonpMainTemplate.runtime'>;
}
declare module 'mpvue-webpack-target/JsonpMainTemplatePlugin.js' {
  declare module.exports: $Exports<'mpvue-webpack-target/JsonpMainTemplatePlugin'>;
}
declare module 'mpvue-webpack-target/JsonpTemplatePlugin.js' {
  declare module.exports: $Exports<'mpvue-webpack-target/JsonpTemplatePlugin'>;
}
