// flow-typed signature: 21e5c762d036e53273102e55259240ad
// flow-typed version: <<STUB>>/mpvue-template-compiler_v^1.0.11/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mpvue-template-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mpvue-template-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mpvue-template-compiler/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mpvue-template-compiler/build.js' {
  declare module.exports: $Exports<'mpvue-template-compiler/build'>;
}
declare module 'mpvue-template-compiler/index' {
  declare module.exports: $Exports<'mpvue-template-compiler'>;
}
declare module 'mpvue-template-compiler/index.js' {
  declare module.exports: $Exports<'mpvue-template-compiler'>;
}
