// flow-typed signature: dbce4b86e0dde81191861588215c386a
// flow-typed version: <<STUB>>/mpvue-loader_v1.0.13/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mpvue-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mpvue-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mpvue-loader/lib/component-normalizer' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/mp-compiler/index' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/mp-compiler/parse-ts' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/mp-compiler/parse' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/mp-compiler/templates' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/mp-compiler/util' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/parser' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/selector' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/style-compiler/index' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/style-compiler/load-postcss-config' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/style-compiler/plugins/scope-id' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/style-compiler/plugins/trim' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/template-compiler/index' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/template-compiler/modules/transform-require' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/template-compiler/preprocessor' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/utils/gen-id' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/utils/normalize' {
  declare module.exports: any;
}

declare module 'mpvue-loader/lib/utils/try-require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mpvue-loader/index' {
  declare module.exports: $Exports<'mpvue-loader'>;
}
declare module 'mpvue-loader/index.js' {
  declare module.exports: $Exports<'mpvue-loader'>;
}
declare module 'mpvue-loader/lib/component-normalizer.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/component-normalizer'>;
}
declare module 'mpvue-loader/lib/loader.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/loader'>;
}
declare module 'mpvue-loader/lib/mp-compiler/index.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/mp-compiler/index'>;
}
declare module 'mpvue-loader/lib/mp-compiler/parse-ts.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/mp-compiler/parse-ts'>;
}
declare module 'mpvue-loader/lib/mp-compiler/parse.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/mp-compiler/parse'>;
}
declare module 'mpvue-loader/lib/mp-compiler/templates.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/mp-compiler/templates'>;
}
declare module 'mpvue-loader/lib/mp-compiler/util.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/mp-compiler/util'>;
}
declare module 'mpvue-loader/lib/parser.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/parser'>;
}
declare module 'mpvue-loader/lib/selector.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/selector'>;
}
declare module 'mpvue-loader/lib/style-compiler/index.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/style-compiler/index'>;
}
declare module 'mpvue-loader/lib/style-compiler/load-postcss-config.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/style-compiler/load-postcss-config'>;
}
declare module 'mpvue-loader/lib/style-compiler/plugins/scope-id.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/style-compiler/plugins/scope-id'>;
}
declare module 'mpvue-loader/lib/style-compiler/plugins/trim.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/style-compiler/plugins/trim'>;
}
declare module 'mpvue-loader/lib/template-compiler/index.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/template-compiler/index'>;
}
declare module 'mpvue-loader/lib/template-compiler/modules/transform-require.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/template-compiler/modules/transform-require'>;
}
declare module 'mpvue-loader/lib/template-compiler/preprocessor.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/template-compiler/preprocessor'>;
}
declare module 'mpvue-loader/lib/utils/gen-id.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/utils/gen-id'>;
}
declare module 'mpvue-loader/lib/utils/normalize.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/utils/normalize'>;
}
declare module 'mpvue-loader/lib/utils/try-require.js' {
  declare module.exports: $Exports<'mpvue-loader/lib/utils/try-require'>;
}
