// flow-typed signature: 56ae25cd3eadfb685ba5f15b545b1261
// flow-typed version: <<STUB>>/mpvue_v^1.0.11/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mpvue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mpvue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mpvue/index' {
  declare module.exports: $Exports<'mpvue'>;
}
declare module 'mpvue/index.js' {
  declare module.exports: $Exports<'mpvue'>;
}
