// flow-typed signature: 4041cc126d2d57a5d0f271be3e5eec25
// flow-typed version: <<STUB>>/postcss-mpvue-wxss_v^1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-mpvue-wxss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-mpvue-wxss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-mpvue-wxss/lib/wxmlTagMap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-mpvue-wxss/index' {
  declare module.exports: $Exports<'postcss-mpvue-wxss'>;
}
declare module 'postcss-mpvue-wxss/index.js' {
  declare module.exports: $Exports<'postcss-mpvue-wxss'>;
}
declare module 'postcss-mpvue-wxss/lib/wxmlTagMap.js' {
  declare module.exports: $Exports<'postcss-mpvue-wxss/lib/wxmlTagMap'>;
}
