// flow-typed signature: 8831d92f0cf485ec4218c34dbefd6517
// flow-typed version: <<STUB>>/px2rpx-loader_v^0.1.10/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'px2rpx-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'px2rpx-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'px2rpx-loader/lib/px2rpx-loader' {
  declare module.exports: any;
}

declare module 'px2rpx-loader/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'px2rpx-loader/index' {
  declare module.exports: $Exports<'px2rpx-loader'>;
}
declare module 'px2rpx-loader/index.js' {
  declare module.exports: $Exports<'px2rpx-loader'>;
}
declare module 'px2rpx-loader/lib/px2rpx-loader.js' {
  declare module.exports: $Exports<'px2rpx-loader/lib/px2rpx-loader'>;
}
declare module 'px2rpx-loader/test.js' {
  declare module.exports: $Exports<'px2rpx-loader/test'>;
}
