// flow-typed signature: 7005cb5c0b482471dafca406cce6a7fe
// flow-typed version: <<STUB>>/webpack-dev-middleware-hard-disk_v^1.12.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware-hard-disk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware-hard-disk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware-hard-disk/lib/GetFilenameFromUrl' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-hard-disk/lib/PathJoin' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-hard-disk/lib/Shared' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-hard-disk/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware-hard-disk/lib/GetFilenameFromUrl.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-hard-disk/lib/GetFilenameFromUrl'>;
}
declare module 'webpack-dev-middleware-hard-disk/lib/PathJoin.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-hard-disk/lib/PathJoin'>;
}
declare module 'webpack-dev-middleware-hard-disk/lib/Shared.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-hard-disk/lib/Shared'>;
}
declare module 'webpack-dev-middleware-hard-disk/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-hard-disk/middleware'>;
}
