// flow-typed signature: df042b8d7d7cfb9472f9cc4bbe55eef1
// flow-typed version: <<STUB>>/webpack-mpvue-asset-plugin_v0.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-mpvue-asset-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-mpvue-asset-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-mpvue-asset-plugin/index' {
  declare module.exports: $Exports<'webpack-mpvue-asset-plugin'>;
}
declare module 'webpack-mpvue-asset-plugin/index.js' {
  declare module.exports: $Exports<'webpack-mpvue-asset-plugin'>;
}
